ALTER TABLE ONLY applications ALTER COLUMN created_at DROP DEFAULT;
ALTER TABLE ONLY kyc_applications ALTER COLUMN created_at DROP DEFAULT;
ALTER TABLE ONLY tokens ALTER COLUMN created_at DROP DEFAULT;
ALTER TABLE ONLY users ALTER COLUMN created_at DROP DEFAULT;
