#!/bin/bash

if [[ -z "${LOG_LEVEL}" ]]; then
  LOG_LEVEL=info
fi

if [[ -z "${DATABASE_HOST}" ]]; then
  DATABASE_HOST=localhost
fi

if [[ -z "${DATABASE_NAME}" ]]; then
  DATABASE_NAME=ident_dev
fi

if [[ -z "${DATABASE_USER}" ]]; then
  DATABASE_USER=ident
fi

if [[ -z "${DATABASE_PASSWORD}" ]]; then
  DATABASE_PASSWORD=
fi

if [[ -z "${DATABASE_SUPERUSER}" ]]; then
  DATABASE_SUPERUSER=prvd
fi

if [[ -z "${DATABASE_SUPERUSER_PASSWORD}" ]]; then
  DATABASE_SUPERUSER_PASSWORD=prvdp455
fi

if [[ -z "${DATABASE_LOGGING}" ]]; then
  DATABASE_LOGGING=false
fi

./ops/await_tcp.sh $DATABASE_HOST

echo ${DATABASE_SUPERUSER_PASSWORD} > ~/.pgpass
chmod 0600 ~/.pgpass
psql -U $DATABASE_SUPERUSER $DATABASE_USER -c "CREATE USER ${DATABASE_USER} SUPERUSER WITH PASSWORD '${DATABASE_PASSWORD}'" 2>/dev/null
psql -U $DATABASE_SUPERUSER $DATABASE_USER -c "CREATE DATABASE ${DATABASE_NAME} OWNER ${DATABASE_USER}" 2>/dev/null
rm ~/.pgpass

DATABASE_HOST=$DATABASE_HOST \
DATABASE_NAME=$DATABASE_NAME \
DATABASE_USER=$DATABASE_USER \
DATABASE_PASSWORD=$DATABASE_PASSWORD \
DATABASE_LOGGING=$DATABASE_LOGGING \
LOG_LEVEL=$LOG_LEVEL \
./.bin/ident_migrate
