#!/bin/bash

if [[ -z "${API_ACCOUNTING_LISTEN_ADDRESS}" ]]; then
  API_ACCOUNTING_LISTEN_ADDRESS=0.0.0.0:8889
fi

if [[ -z "${LOG_LEVEL}" ]]; then
  LOG_LEVEL=debug
fi

if [[ -z "${DATABASE_HOST}" ]]; then
  DATABASE_HOST=0.0.0.0
fi

if [[ -z "${DATABASE_NAME}" ]]; then
  DATABASE_NAME=ident_dev
fi

if [[ -z "${DATABASE_USER}" ]]; then
  DATABASE_USER=ident
fi

if [[ -z "${DATABASE_PASSWORD}" ]]; then
  DATABASE_PASSWORD=
fi

if [[ -z "${DATABASE_LOGGING}" ]]; then
  DATABASE_LOGGING=false
fi

LOG_LEVEL=$LOG_LEVEL \
DATABASE_HOST=$DATABASE_HOST \
DATABASE_NAME=$DATABASE_NAME \
DATABASE_USER=$DATABASE_USER \
DATABASE_PASSWORD=$DATABASE_PASSWORD \
DATABASE_LOGGING=$DATABASE_LOGGING \
SYSLOG_ENDPOINT=${SYSLOG_ENDPOINT} \
API_ACCOUNTING_LISTEN_ADDRESS=$API_ACCOUNTING_LISTEN_ADDRESS \
./.bin/ident_api_accountant
