name: dev-integration-test-scheduled
on:
  schedule:
    - cron: '0 * * * *'  # every hour on the hour     
jobs:
  integration-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10    
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.INTEGRATION_SLACK_WEBHOOK }}
    steps:
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.1'
      - name: Checkout ident
        uses: actions/checkout@v2
        with:
          path: 'ident'                      
      - run: docker-compose -f ./ops/docker-compose-integration.yml build --no-cache ident
        working-directory: ident
      - run: docker-compose -f ./ops/docker-compose-integration.yml up -d
        working-directory: ident
      - run: TAGS=integration ./ops/run_local_tests_long.sh
        working-directory: ident      
      - run: docker-compose -f ./ops/docker-compose.yml logs
        working-directory: ident
      - name: slack channel update
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: always()    