name: dev-integration-test
on:
  push:
    branches:
      - dev
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.1'
      - name: Checkout ident
        uses: actions/checkout@v2
        with:
          path: 'ident'                      
      - run: make integration
        working-directory: ident