on: 
  push:
    branches:
      - dev

jobs:
  push_to_branch:
    runs-on: ubuntu-latest
    timeout-minutes: 10    
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.INTEGRATION_SLACK_WEBHOOK }}
    steps:
      - name: set_up_environment
        id: setup
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.1'
      - name: checkout_and_run_tests
        id: tests
        uses: actions/checkout@v2
        with:
          path: 'ident'                  
      - run: docker-compose -f ./ops/docker-compose.yml build --no-cache ident
        working-directory: ident
      - run: docker-compose -f ./ops/docker-compose.yml up -d
        working-directory: ident
      - run: TAGS=integration ./ops/run_local_tests_long.sh
        working-directory: ident      
      - run: docker-compose -f ./ops/docker-compose.yml logs
        working-directory: ident
      - name: push_to_docker_hub
        if: success()
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PAT }}
          repository: provide/ident
          tags: dev
          path: 'ident'
      - name: slack channel update
        if: failure()  
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        