name: integration-test
on:
  push:
    branches:
      - integration
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout ident
        uses: actions/checkout@v2
        with:
          path: 'ident'        
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.1'
      - name: Checkout integration test
        uses: actions/checkout@v2
        with:
          repository: provideapp/integration
          path: 'integration'
          ref: master
          token: ${{ secrets.PAT }}          
      - run: docker-compose -f ./ops/docker-compose-integration.yml up -d
        working-directory: ident
      - run:     make integration_ident                                   
        working-directory: integration       
      - run: docker-compose -f ./ops/docker-compose-integration.yml down
        working-directory: ident
      - run: docker volume rm ops_vault-db