name: integration-test
on:
  push:
    branches:
      - dev
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.1'
      - name: Checkout ident
        uses: actions/checkout@v2
        with:
          path: 'ident' 
      - name: Checkout vault
        uses: actions/checkout@v2
        with:
          repository: provideapp/vault
          path: 'vault'
          ref: dev
          token: ${{ secrets.DEPLOY_GITHUB_PAT }}                           
      - name: Checkout integration test
        uses: actions/checkout@v2
        with:
          repository: provideapp/integration
          path: 'integration'
          ref: master
          token: ${{ secrets.DEPLOY_GITHUB_PAT }}          
      - run: docker-compose -f ./ops/docker-compose-integration.yml up -d
        working-directory: ident
      - run:     TAGS=ident ./ops/run_local_tests.sh                                   
        working-directory: integration       
      - run: docker-compose -f ./ops/docker-compose-integration.yml down
        working-directory: ident
      - run: docker volume rm ops_vault-db